### ISSUE TITLE
I'd like to see the "if you're my friend, then I'm your friend" case

### ISSUE THREAD

**Issue by jaredroach** [statnet/COVID-JustOneFriend#13]
The simplest English interpretation of "Just one friend" is that friendship is mutual. That is, if you are my one friend, then I am your one friend. The exposition seems to lack this example.

**Comment by martinamorris** [comment]
Aha -- the nodes in our network are *households*, not people.  Some of the press reporting on this got that point wrong.  Does that answer your question?

**Comment by jaredroach** [comment]
Focusing on the nodes - I envisage a model where every node is given one random node to another random node -> that would be the "Just one friend model". the way to code this would be to 

Create a list of all nodes (order doesn't matter)
While that list of nodes has at least two nodes in it
      Add an edge between two random nodes in the list
      Remove those two nodes from the list
End

My understanding of the current model (which I think is better titled the "two friends" model) is

Create a list of all nodes (order doesn't matter)
Foreach node in that list
     Add an edge to another node in the list
End

In this second model, on average each node gets one new incoming edge and one new outgoing edge - so two new edges. In the first model, each node (possibly with one left over if an odd number of nodes) gets exactly one new edge.

**Comment by martinamorris** [comment]
All the code is up on GitHub in a public repository -- linked in the last section of the report IIRC.  I've got a lot on right now so won't be able to respond for several hours.  Feel free to fork and play!

**Comment by sgoodreau** [comment]
Thanks Jared! The model you're describing is, I believe, exactly what the final example on our page does.  (The "exactly one friend per household" case).  Some of the reporting only focused on the "one friend per person, for an average of two persons per household" case.  Check it out and see if it represents what you mean.

**Comment by jaredroach** [comment]
OK. Thanks. You are correct. Looking closely, the graph shows that "just one friend" is fine as long as neither friend is from an "essential worker family". I think this point was lost in the press.

**Comment by jaredroach** [comment]
I think one of the reasons it didn't make it into that press coverage is the lack of discussion that this scenario actually suggests: that it is OK in some circumstances to make contacts. The discussion at the end of the blog has in bold these two sentences: 
"Every additional connection that we can postpone until COVID-19 is under control has the potential to save one or more lives. Yes, every one."
and
"Regardless of who it is—waiting a bit to hang out with your friends again is worth it!"
The data don't support these conclusions. There are some circumstances where it is worth it. These are the barbells in Figure 6, for example.
Society desperately needs evidence-based metrics for increasing productivity. For two single parents that are not otherwise network connected, it seems reasonable for them to share childcare if that allows them to free up enough personal productivity to do things like survive, contribute to the pandemic response, and/or produce value (e.g., economic). Details are important in each case. The quantitative risks and benefits must be weighed.

**Comment by martinamorris** [comment]
@jaredroach I agree with your assessment.  Our goal was to address the *immediate* need to continue the more dramatic form of social distancing, until we see the evidence from public health surveillance data on mortality counts and hospital admissions to relax it.  We are already seeking to extend this app to be able to provide more nuanced guidelines once we are in a position to start relaxing them.

**Comment by dth2** [comment]
@jaredroach @martinamorris I would also add that these networks are static representations but life is dynamic.  Presumably every household will at some point need food or other goods so at some point every house will be connected to a house with an essential worker.  So even when seemingly unconnected households are joined in a barbell there is a false sense of isolation because both of those households will at some point be connected to the outside world.  As a consequence those barbells connections will, in reality, contribute to the overall connectivity and risk in the network when temporal dynamics are considered.

**Comment by martinamorris** [comment]
@dth2 and when we add dynamics, we need to get more detailed about the intensity of exposure for each tie, to accurately reflect risk.  a full blown dynamic network epidemic model would require significantly more work, and would rely on all of the parameters that are still highly uncertain:  the length of the pre-symptomatic period, fraction of cases that will be asymptomatic, transmission probabilities under different circumstances, as well as use of protective gear and frequency/duration of contact.  It's not hard to build a model for this.  But the projections are only as good as the inputs.

**Comment by jaredroach** [comment]
@dth2 <p>In that case, the original parameters of the entire blog are wrong. All the graphs currently in the blog include some isolated nodes to start with. And if we stipulate every node is highly connected to start with, there won't be much further point in doing these analyses. We will all be toast (e.g., R<sub>e</sub> >> 1) before we add in <i>any</i> more single links.<p><p>@martinamorris<p>Yes. We really need to be able to answer questions about what effect certain policy decisions might have on the effective reproduction rate. For example, if we allow urgent but not essential dentistry (e.g. broken tooth extraction), what would the effect on R<sub>e</sub> be?

**Comment by martinamorris** [comment]
@jaredroach No, it's not all wrong.  Links are used to show repeated/close contact.  Not all HH have that.

i suspect we'll never be able to get the certainty you're hoping for.  there just won't be input parameters to answer a question like urgent but not essential dentistry without years of clinical trials that would be massively expensive to conduct.

again, the purpose of this exercise was to convey that network can become highly connected, even if most nodes have only 1 or 2 connections.  that may not be a surprise to you, but given the feedback we've had, it is a surprise to most people.

**Comment by dth2** [comment]
@jaredroach I don't want to go down the rabbit hole of static Vs dynamic networks and all of the various parameters involved.  That may be for another model. This particular tool is used for illustrative purposes, it is static and the parameters reflect that. I would just caution against drawing the conclusion that some ties are safe because they link isolated houses.

**Comment by jaredroach** [comment]
@martinamorris<p>I'm not hoping for certainty (if you can point out the text in the thread that implied a desire for certainty I will go back and edit it). But I am worried about backlash if policy decisions are made based on models that aren't appropriately nuanced. As stated above, the real issue I have is with the <b>bolded</b> conclusions at the end of the blog that were not supported by the analysis provided in the blog.

**Comment by sgoodreau** [comment]
My two thoughts, and then I will bow out of this thread.  

This tool is meant to communicate a single general well-understood principle about network connectivity to a broad audience, with a special goal of reaching youth.  In that context, I think of it as akin to an exhibit at a science museum, with all of the limitations that entails. It is not in any way set up to be a policy assessment tool, which is an endeavor multiple orders of magnitude more complex. I know multiple folks who are submitting research proposals to do work in that vein, but that will take many weeks to months of dedicated time.

There are, of course, many kinds of relationships in the real world beyond just work relationships for essential workers and friendships for everybody.  Childcare is one of them. You will notice that we even mention a form of that one in the caveats section at the end, in terms of blended households. This specific inclusion was inspired by my close friend who has joint custody of her children right now.

The very title of the site, and every paragraph thereafter, and all of the statements I've made to the press, focus on one goal only: getting people to re-consider one very specific type of relationship that is truly optional: hanging out in person with friends for no reason other than to socialize.  And getting people to realize that engaging in this relationship right now adds exposure risk to everyone else who has some kind of in-person relationship they need to maintain. Again, with a specific desire to reach young people who may not be used to thinking in terms of such trade-offs.
